experiment: ''
seed: 42
amp: true
# amp: false

# dataset parameters
batch_size: 64 #128or256 on paper
val_batch_size: 64
data_dir: /dataset/ILSVRC2012

# training parameters
epochs: 300
lr: 5e-4 #5e-4 on paper
min_lr: 2.0e-05
warmup_epochs: 20
warmup_lr: 1.0e-05
sched: cosine

# model parameters
model: sdt
time_steps: 4
spike_mode: lif
layer: 8
dim: 768
# mlp-ratio: 4
# mlp_ratio: 4
mlp_ratio: 1.0
num_experts: 4
expert_timesteps: [4, 1, 1, 1] #"--expert-timesteps",
only_expert_ids: null




aa: rand-m7-mstd0.5-inc1

apex_amp: false
aug_repeats: 3
aug_splits: 0

bce-loss: true
bce-target-thresh: 0.2
bce_loss: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
bn_tf: false
channels-last: false
channels_last: false
checkpoint_hist: 10
clip_grad: null
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: 0.95
cutmix: 1.0
cutmix_minmax: null

dataset: imagenet
decay_epochs: 30
decay_rate: 0.1

dist_bn: ''
drop: 0.0
drop_block: null
drop_connect: null
drop_path: 0.2
dvs_aug: false
dvs_trival_aug: false
epoch_repeats: 0.0

eval_metric: top1

gp: null
hflip: 0.5
img_size: 224
in_channels: 3
initial_checkpoint: ''
input_size: null
interpolation: bicubic
jsd: false

# local_rank: 0
log_interval: 100
log_wandb: false

lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean:
- 0.485
- 0.456
- 0.406

mixup: 0.2
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5


model-ema: false
model-ema-decay: 0.9998
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_prefetcher: false
no_resume_opt: false
num_classes: 1000
num_heads: 8
opt: lamb
opt_betas: null
opt_eps: null
output: ''
patch_size: null
patience_epochs: 10
pin_mem: false
pooling_stat: '1111'
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: const
reprob: 0.0
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0


smoothing: 0.1

split_bn: false
start_epoch: null
std:
- 0.229
- 0.224
- 0.225
sync_bn: false

torchscript: false
train_interpolation: bicubic
train_split: train
tta: 0
use_conv_as_linear: true
use_multi_epochs_loader: false

val_split: validation
vflip: 0.0

weight_decay: 0.01
workers: 8


